<?php

namespace AppBundle\Repository;

/**
 * Article_CommentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Article_CommentRepository extends \Doctrine\ORM\EntityRepository
{
}
